apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
  storageClassName: nfs-delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-test
  namespace: default
  labels:
    app: nfs-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-test
  template:
    metadata:
      labels:
        app: nfs-test
    spec:
      nodeSelector:
        nfs: client
      containers:
      - name: alpine
        image: docker.io/library/alpine:latest
        imagePullPolicy: IfNotPresent
        command: [ "sleep" ]
        args: [ "infinity" ]
        resources:
          requests:
            cpu: "50m"
            memory: "5Mi"
          limits:
            cpu: "100m"
            memory: "10Mi"
        volumeMounts:
          - name: nfs-test
            mountPath: /var/nfstest
            readOnly: true
      volumes:
        - name: nfs-test
          persistentVolumeClaim:
            claimName: nfs-test-pvc
